import tkinter as tk

#class Board(tk.Tk):
class Board(tk.Frame):

    def __init__(self, master, colors):
        super().__init__()

        self.master = master

        # colors
        self.back_color    = colors["back_color"]
        self.player0_color = colors["player0_color"]
        self.player1_color = colors["player1_color"]
        self.player2_color = colors["player2_color"]
        self.player3_color = colors["player3_color"]
        self.player4_color = colors["player4_color"]
        self.player_colors = [self.player1_color, self.player2_color, self.player3_color, self.player4_color]
        self.house_color   = colors["house_color"]
        self.stone_color   = colors["stone_color"]
        self.electr_color  = colors["electr_color"]
        self.food_color    = colors["food_color"]
        self.corner_color  = colors["corner_color"]


        # board
        #self.title("My Board")
        #self.geometry("600x600")
        self.configure(background=self.back_color)


        # corner fields

        self.nw_field = tk.Label(self, text="skip a\nturn", bg=self.corner_color, bd=0)
        self.nw_field.grid(row=1, column=0, columnspan=2, sticky="wens")

        self.nw_pos = tk.Frame(self, bd=0)
        self.nw_pos.grid(row=0, column=0, columnspan=2, sticky="wens")
        self.nw_pos.columnconfigure((0,1,2,3), weight=1)
        self.nw_pos.rowconfigure(0, weight=1)
        self.nw_player_1 = tk.Frame(self.nw_pos, bg=self.corner_color)
        self.nw_player_1.grid(row=0, column=3, sticky="wens")
        self.nw_player_2 = tk.Frame(self.nw_pos, bg=self.corner_color)
        self.nw_player_2.grid(row=0, column=2, sticky="wens")
        self.nw_player_3 = tk.Frame(self.nw_pos, bg=self.corner_color)
        self.nw_player_3.grid(row=0, column=1, sticky="wens")
        self.nw_player_4 = tk.Frame(self.nw_pos, bg=self.corner_color)
        self.nw_player_4.grid(row=0, column=0, sticky="wens")

        self.ne_field = tk.Label(self, text="roll again,\nmove\nbackward", bg=self.corner_color, bd=0)
        self.ne_field.grid(row=1, column=10, columnspan=2, sticky="wens")

        self.ne_pos = tk.Frame(self, bd=0)
        self.ne_pos.grid(row=0, column=10, columnspan=2, sticky="wens")
        self.ne_pos.columnconfigure((0,1,2,3), weight=1)
        self.ne_pos.rowconfigure(0, weight=1)
        self.ne_player_1 = tk.Frame(self.ne_pos, bg=self.corner_color)
        self.ne_player_1.grid(row=0, column=3, sticky="wens")
        self.ne_player_2 = tk.Frame(self.ne_pos, bg=self.corner_color)
        self.ne_player_2.grid(row=0, column=2, sticky="wens")
        self.ne_player_3 = tk.Frame(self.ne_pos, bg=self.corner_color)
        self.ne_player_3.grid(row=0, column=1, sticky="wens")
        self.ne_player_4 = tk.Frame(self.ne_pos, bg=self.corner_color)
        self.ne_player_4.grid(row=0, column=0, sticky="wens")

        self.sw_field = tk.Label(self, text="roll again,\nmove\nforward", bg=self.corner_color, bd=0)
        self.sw_field.grid(row=10, column=0, columnspan=2, sticky="wens")

        self.sw_pos = tk.Frame(self, bd=0)
        self.sw_pos.grid(row=11, column=0, columnspan=2, sticky="wens")
        self.sw_pos.columnconfigure((0,1,2,3), weight=1)
        self.sw_pos.rowconfigure(0, weight=1)
        self.sw_player_1 = tk.Frame(self.sw_pos, bg=self.corner_color)
        self.sw_player_1.grid(row=0, column=0, sticky="wens")
        self.sw_player_2 = tk.Frame(self.sw_pos, bg=self.corner_color)
        self.sw_player_2.grid(row=0, column=1, sticky="wens")
        self.sw_player_3 = tk.Frame(self.sw_pos, bg=self.corner_color)
        self.sw_player_3.grid(row=0, column=2, sticky="wens")
        self.sw_player_4 = tk.Frame(self.sw_pos, bg=self.corner_color)
        self.sw_player_4.grid(row=0, column=3, sticky="wens")

        self.se_field = tk.Label(self, text="GO!", bg=self.corner_color, bd=0)
        self.se_field.grid(row=10, column=10, columnspan=2, sticky="wens")

        self.se_pos = tk.Frame(self, bd=0)
        self.se_pos.grid(row=11, column=10, columnspan=2, sticky="wens")
        self.se_pos.columnconfigure((0,1,2,3), weight=1)
        self.se_pos.rowconfigure(0, weight=1)
        self.se_player_1 = tk.Frame(self.se_pos, bg=self.player1_color)
        self.se_player_1.grid(row=0, column=0, sticky="wens")
        self.se_player_2 = tk.Frame(self.se_pos, bg=self.player2_color)
        self.se_player_2.grid(row=0, column=1, sticky="wens")
        self.se_player_3 = tk.Frame(self.se_pos, bg=self.player3_color)
        self.se_player_3.grid(row=0, column=2, sticky="wens")
        self.se_player_4 = tk.Frame(self.se_pos, bg=self.player4_color)
        self.se_player_4.grid(row=0, column=3, sticky="wens")


        # north fields

        self.n1_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n1_field.grid(row=1, column=2, sticky="wens")
        self.n1_button = tk.Button(self.n1_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.n1_button.grid(row=0, column=0, sticky="wens")
        self.n1_field.rowconfigure(0, weight=1)
        self.n1_field.columnconfigure(0, weight=1)

        self.n1_pos = tk.Frame(self, bd=0)
        self.n1_pos.grid(row=0, column=2, sticky="wens")
        self.n1_pos.columnconfigure((0,1,2,3), weight=1)
        self.n1_pos.rowconfigure(0, weight=1)
        self.n1_player_1 = tk.Frame(self.n1_pos, bg=self.back_color)
        self.n1_player_1.grid(row=0, column=3, sticky="wens")
        self.n1_player_2 = tk.Frame(self.n1_pos, bg=self.back_color)
        self.n1_player_2.grid(row=0, column=2, sticky="wens")
        self.n1_player_3 = tk.Frame(self.n1_pos, bg=self.back_color)
        self.n1_player_3.grid(row=0, column=1, sticky="wens")
        self.n1_player_4 = tk.Frame(self.n1_pos, bg=self.back_color)
        self.n1_player_4.grid(row=0, column=0, sticky="wens")

        self.n2_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n2_field.grid(row=1, column=3, sticky="wens")
        self.n2_button = tk.Button(self.n2_field, text="", bg=self.electr_color, state=tk.DISABLED)
        self.n2_button.grid(row=0, column=0, sticky="wens")
        self.n2_field.rowconfigure(0, weight=1)
        self.n2_field.columnconfigure(0, weight=1)

        self.n2_pos = tk.Frame(self, bd=0)
        self.n2_pos.grid(row=0, column=3, sticky="wens")
        self.n2_pos.columnconfigure((0,1,2,3), weight=1)
        self.n2_pos.rowconfigure(0, weight=1)
        self.n2_player_1 = tk.Frame(self.n2_pos, bg=self.back_color)
        self.n2_player_1.grid(row=0, column=3, sticky="wens")
        self.n2_player_2 = tk.Frame(self.n2_pos, bg=self.back_color)
        self.n2_player_2.grid(row=0, column=2, sticky="wens")
        self.n2_player_3 = tk.Frame(self.n2_pos, bg=self.back_color)
        self.n2_player_3.grid(row=0, column=1, sticky="wens")
        self.n2_player_4 = tk.Frame(self.n2_pos, bg=self.back_color)
        self.n2_player_4.grid(row=0, column=0, sticky="wens")

        self.n3_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n3_field.grid(row=1, column=4, sticky="wens")
        self.n3_button = tk.Button(self.n3_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.n3_button.grid(row=0, column=0, sticky="wens")
        self.n3_field.rowconfigure(0, weight=1)
        self.n3_field.columnconfigure(0, weight=1)

        self.n3_pos = tk.Frame(self, bd=0)
        self.n3_pos.grid(row=0, column=4, sticky="wens")
        self.n3_pos.columnconfigure((0,1,2,3), weight=1)
        self.n3_pos.rowconfigure(0, weight=1)
        self.n3_player_1 = tk.Frame(self.n3_pos, bg=self.back_color)
        self.n3_player_1.grid(row=0, column=3, sticky="wens")
        self.n3_player_2 = tk.Frame(self.n3_pos, bg=self.back_color)
        self.n3_player_2.grid(row=0, column=2, sticky="wens")
        self.n3_player_3 = tk.Frame(self.n3_pos, bg=self.back_color)
        self.n3_player_3.grid(row=0, column=1, sticky="wens")
        self.n3_player_4 = tk.Frame(self.n3_pos, bg=self.back_color)
        self.n3_player_4.grid(row=0, column=0, sticky="wens")

        self.n4_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n4_field.grid(row=1, column=5, sticky="wens")
        self.n4_button = tk.Button(self.n4_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.n4_button.grid(row=0, column=0, sticky="wens")
        self.n4_field.rowconfigure(0, weight=1)
        self.n4_field.columnconfigure(0, weight=1)

        self.n4_pos = tk.Frame(self, bd=0)
        self.n4_pos.grid(row=0, column=5, sticky="wens")
        self.n4_pos.columnconfigure((0,1,2,3), weight=1)
        self.n4_pos.rowconfigure(0, weight=1)
        self.n4_player_1 = tk.Frame(self.n4_pos, bg=self.back_color)
        self.n4_player_1.grid(row=0, column=3, sticky="wens")
        self.n4_player_2 = tk.Frame(self.n4_pos, bg=self.back_color)
        self.n4_player_2.grid(row=0, column=2, sticky="wens")
        self.n4_player_3 = tk.Frame(self.n4_pos, bg=self.back_color)
        self.n4_player_3.grid(row=0, column=1, sticky="wens")
        self.n4_player_4 = tk.Frame(self.n4_pos, bg=self.back_color)
        self.n4_player_4.grid(row=0, column=0, sticky="wens")

        self.n5_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n5_field.grid(row=1, column=6, sticky="wens")
        self.n5_button = tk.Button(self.n5_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.n5_button.grid(row=0, column=0, sticky="wens")
        self.n5_field.rowconfigure(0, weight=1)
        self.n5_field.columnconfigure(0, weight=1)

        self.n5_pos = tk.Frame(self, bd=0)
        self.n5_pos.grid(row=0, column=6, sticky="wens")
        self.n5_pos.columnconfigure((0,1,2,3), weight=1)
        self.n5_pos.rowconfigure(0, weight=1)
        self.n5_player_1 = tk.Frame(self.n5_pos, bg=self.back_color)
        self.n5_player_1.grid(row=0, column=3, sticky="wens")
        self.n5_player_2 = tk.Frame(self.n5_pos, bg=self.back_color)
        self.n5_player_2.grid(row=0, column=2, sticky="wens")
        self.n5_player_3 = tk.Frame(self.n5_pos, bg=self.back_color)
        self.n5_player_3.grid(row=0, column=1, sticky="wens")
        self.n5_player_4 = tk.Frame(self.n5_pos, bg=self.back_color)
        self.n5_player_4.grid(row=0, column=0, sticky="wens")

        self.n6_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n6_field.grid(row=1, column=7, sticky="wens")
        self.n6_button = tk.Button(self.n6_field, text="", bg=self.food_color, state=tk.DISABLED)
        self.n6_button.grid(row=0, column=0, sticky="wens")
        self.n6_field.rowconfigure(0, weight=1)
        self.n6_field.columnconfigure(0, weight=1)

        self.n6_pos = tk.Frame(self, bd=0)
        self.n6_pos.grid(row=0, column=7, sticky="wens")
        self.n6_pos.columnconfigure((0,1,2,3), weight=1)
        self.n6_pos.rowconfigure(0, weight=1)
        self.n6_player_1 = tk.Frame(self.n6_pos, bg=self.back_color)
        self.n6_player_1.grid(row=0, column=3, sticky="wens")
        self.n6_player_2 = tk.Frame(self.n6_pos, bg=self.back_color)
        self.n6_player_2.grid(row=0, column=2, sticky="wens")
        self.n6_player_3 = tk.Frame(self.n6_pos, bg=self.back_color)
        self.n6_player_3.grid(row=0, column=1, sticky="wens")
        self.n6_player_4 = tk.Frame(self.n6_pos, bg=self.back_color)
        self.n6_player_4.grid(row=0, column=0, sticky="wens")

        self.n7_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n7_field.grid(row=1, column=8, sticky="wens")
        self.n7_button = tk.Button(self.n7_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.n7_button.grid(row=0, column=0, sticky="wens")
        self.n7_field.rowconfigure(0, weight=1)
        self.n7_field.columnconfigure(0, weight=1)

        self.n7_pos = tk.Frame(self, bd=0)
        self.n7_pos.grid(row=0, column=8, sticky="wens")
        self.n7_pos.columnconfigure((0,1,2,3), weight=1)
        self.n7_pos.rowconfigure(0, weight=1)
        self.n7_player_1 = tk.Frame(self.n7_pos, bg=self.back_color)
        self.n7_player_1.grid(row=0, column=3, sticky="wens")
        self.n7_player_2 = tk.Frame(self.n7_pos, bg=self.back_color)
        self.n7_player_2.grid(row=0, column=2, sticky="wens")
        self.n7_player_3 = tk.Frame(self.n7_pos, bg=self.back_color)
        self.n7_player_3.grid(row=0, column=1, sticky="wens")
        self.n7_player_4 = tk.Frame(self.n7_pos, bg=self.back_color)
        self.n7_player_4.grid(row=0, column=0, sticky="wens")

        self.n8_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.n8_field.grid(row=1, column=9, sticky="wens")
        self.n8_button = tk.Button(self.n8_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.n8_button.grid(row=0, column=0, sticky="wens")
        self.n8_field.rowconfigure(0, weight=1)
        self.n8_field.columnconfigure(0, weight=1)

        self.n8_pos = tk.Frame(self, bd=0)
        self.n8_pos.grid(row=0, column=9, sticky="wens")
        self.n8_pos.columnconfigure((0,1,2,3), weight=1)
        self.n8_pos.rowconfigure(0, weight=1)
        self.n8_player_1 = tk.Frame(self.n8_pos, bg=self.back_color)
        self.n8_player_1.grid(row=0, column=3, sticky="wens")
        self.n8_player_2 = tk.Frame(self.n8_pos, bg=self.back_color)
        self.n8_player_2.grid(row=0, column=2, sticky="wens")
        self.n8_player_3 = tk.Frame(self.n8_pos, bg=self.back_color)
        self.n8_player_3.grid(row=0, column=1, sticky="wens")
        self.n8_player_4 = tk.Frame(self.n8_pos, bg=self.back_color)
        self.n8_player_4.grid(row=0, column=0, sticky="wens")


        # south fields

        self.s1_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s1_field.grid(row=10, column=9, sticky="wens")
        self.s1_button = tk.Button(self.s1_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.s1_button.grid(row=0, column=0, sticky="wens")
        self.s1_field.rowconfigure(0, weight=1)
        self.s1_field.columnconfigure(0, weight=1)

        self.s1_pos = tk.Frame(self, bd=0)
        self.s1_pos.grid(row=11, column=9, sticky="wens")
        self.s1_pos.columnconfigure((0,1,2,3), weight=1)
        self.s1_pos.rowconfigure(0, weight=1)
        self.s1_player_1 = tk.Frame(self.s1_pos, bg=self.back_color)
        self.s1_player_1.grid(row=0, column=0, sticky="wens")
        self.s1_player_2 = tk.Frame(self.s1_pos, bg=self.back_color)
        self.s1_player_2.grid(row=0, column=1, sticky="wens")
        self.s1_player_3 = tk.Frame(self.s1_pos, bg=self.back_color)
        self.s1_player_3.grid(row=0, column=2, sticky="wens")
        self.s1_player_4 = tk.Frame(self.s1_pos, bg=self.back_color)
        self.s1_player_4.grid(row=0, column=3, sticky="wens")

        self.s2_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s2_field.grid(row=10, column=8, sticky="wens")
        self.s2_button = tk.Button(self.s2_field, text="", bg=self.food_color, state=tk.DISABLED)
        self.s2_button.grid(row=0, column=0, sticky="wens")
        self.s2_field.rowconfigure(0, weight=1)
        self.s2_field.columnconfigure(0, weight=1)

        self.s2_pos = tk.Frame(self, bd=0)
        self.s2_pos.grid(row=11, column=8, sticky="wens")
        self.s2_pos.columnconfigure((0,1,2,3), weight=1)
        self.s2_pos.rowconfigure(0, weight=1)
        self.s2_player_1 = tk.Frame(self.s2_pos, bg=self.back_color)
        self.s2_player_1.grid(row=0, column=0, sticky="wens")
        self.s2_player_2 = tk.Frame(self.s2_pos, bg=self.back_color)
        self.s2_player_2.grid(row=0, column=1, sticky="wens")
        self.s2_player_3 = tk.Frame(self.s2_pos, bg=self.back_color)
        self.s2_player_3.grid(row=0, column=2, sticky="wens")
        self.s2_player_4 = tk.Frame(self.s2_pos, bg=self.back_color)
        self.s2_player_4.grid(row=0, column=3, sticky="wens")

        self.s3_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s3_field.grid(row=10, column=7, sticky="wens")
        self.s3_button = tk.Button(self.s3_field, text="", bg=self.electr_color, state=tk.DISABLED)
        self.s3_button.grid(row=0, column=0, sticky="wens")
        self.s3_field.rowconfigure(0, weight=1)
        self.s3_field.columnconfigure(0, weight=1)

        self.s3_pos = tk.Frame(self, bd=0)
        self.s3_pos.grid(row=11, column=7, sticky="wens")
        self.s3_pos.columnconfigure((0,1,2,3), weight=1)
        self.s3_pos.rowconfigure(0, weight=1)
        self.s3_player_1 = tk.Frame(self.s3_pos, bg=self.back_color)
        self.s3_player_1.grid(row=0, column=0, sticky="wens")
        self.s3_player_2 = tk.Frame(self.s3_pos, bg=self.back_color)
        self.s3_player_2.grid(row=0, column=1, sticky="wens")
        self.s3_player_3 = tk.Frame(self.s3_pos, bg=self.back_color)
        self.s3_player_3.grid(row=0, column=2, sticky="wens")
        self.s3_player_4 = tk.Frame(self.s3_pos, bg=self.back_color)
        self.s3_player_4.grid(row=0, column=3, sticky="wens")

        self.s4_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s4_field.grid(row=10, column=6, sticky="wens")
        self.s4_button = tk.Button(self.s4_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.s4_button.grid(row=0, column=0, sticky="wens")
        self.s4_field.rowconfigure(0, weight=1)
        self.s4_field.columnconfigure(0, weight=1)

        self.s4_pos = tk.Frame(self, bd=0)
        self.s4_pos.grid(row=11, column=6, sticky="wens")
        self.s4_pos.columnconfigure((0,1,2,3), weight=1)
        self.s4_pos.rowconfigure(0, weight=1)
        self.s4_player_1 = tk.Frame(self.s4_pos, bg=self.back_color)
        self.s4_player_1.grid(row=0, column=0, sticky="wens")
        self.s4_player_2 = tk.Frame(self.s4_pos, bg=self.back_color)
        self.s4_player_2.grid(row=0, column=1, sticky="wens")
        self.s4_player_3 = tk.Frame(self.s4_pos, bg=self.back_color)
        self.s4_player_3.grid(row=0, column=2, sticky="wens")
        self.s4_player_4 = tk.Frame(self.s4_pos, bg=self.back_color)
        self.s4_player_4.grid(row=0, column=3, sticky="wens")

        self.s5_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s5_field.grid(row=10, column=5, sticky="wens")
        self.s5_button = tk.Button(self.s5_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.s5_button.grid(row=0, column=0, sticky="wens")
        self.s5_field.rowconfigure(0, weight=1)
        self.s5_field.columnconfigure(0, weight=1)

        self.s5_pos = tk.Frame(self, bd=0)
        self.s5_pos.grid(row=11, column=5, sticky="wens")
        self.s5_pos.columnconfigure((0,1,2,3), weight=1)
        self.s5_pos.rowconfigure(0, weight=1)
        self.s5_player_1 = tk.Frame(self.s5_pos, bg=self.back_color)
        self.s5_player_1.grid(row=0, column=0, sticky="wens")
        self.s5_player_2 = tk.Frame(self.s5_pos, bg=self.back_color)
        self.s5_player_2.grid(row=0, column=1, sticky="wens")
        self.s5_player_3 = tk.Frame(self.s5_pos, bg=self.back_color)
        self.s5_player_3.grid(row=0, column=2, sticky="wens")
        self.s5_player_4 = tk.Frame(self.s5_pos, bg=self.back_color)
        self.s5_player_4.grid(row=0, column=3, sticky="wens")

        self.s6_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s6_field.grid(row=10, column=4, sticky="wens")
        self.s6_button = tk.Button(self.s6_field, text="", bg=self.food_color, state=tk.DISABLED)
        self.s6_button.grid(row=0, column=0, sticky="wens")
        self.s6_field.rowconfigure(0, weight=1)
        self.s6_field.columnconfigure(0, weight=1)

        self.s6_pos = tk.Frame(self, bd=0)
        self.s6_pos.grid(row=11, column=4, sticky="wens")
        self.s6_pos.columnconfigure((0,1,2,3), weight=1)
        self.s6_pos.rowconfigure(0, weight=1)
        self.s6_player_1 = tk.Frame(self.s6_pos, bg=self.back_color)
        self.s6_player_1.grid(row=0, column=0, sticky="wens")
        self.s6_player_2 = tk.Frame(self.s6_pos, bg=self.back_color)
        self.s6_player_2.grid(row=0, column=1, sticky="wens")
        self.s6_player_3 = tk.Frame(self.s6_pos, bg=self.back_color)
        self.s6_player_3.grid(row=0, column=2, sticky="wens")
        self.s6_player_4 = tk.Frame(self.s6_pos, bg=self.back_color)
        self.s6_player_4.grid(row=0, column=3, sticky="wens")

        self.s7_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s7_field.grid(row=10, column=3, sticky="wens")
        self.s7_button = tk.Button(self.s7_field, text="", bg=self.electr_color, state=tk.DISABLED)
        self.s7_button.grid(row=0, column=0, sticky="wens")
        self.s7_field.rowconfigure(0, weight=1)
        self.s7_field.columnconfigure(0, weight=1)

        self.s7_pos = tk.Frame(self, bd=0)
        self.s7_pos.grid(row=11, column=3, sticky="wens")
        self.s7_pos.columnconfigure((0,1,2,3), weight=1)
        self.s7_pos.rowconfigure(0, weight=1)
        self.s7_player_1 = tk.Frame(self.s7_pos, bg=self.back_color)
        self.s7_player_1.grid(row=0, column=0, sticky="wens")
        self.s7_player_2 = tk.Frame(self.s7_pos, bg=self.back_color)
        self.s7_player_2.grid(row=0, column=1, sticky="wens")
        self.s7_player_3 = tk.Frame(self.s7_pos, bg=self.back_color)
        self.s7_player_3.grid(row=0, column=2, sticky="wens")
        self.s7_player_4 = tk.Frame(self.s7_pos, bg=self.back_color)
        self.s7_player_4.grid(row=0, column=3, sticky="wens")

        self.s8_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.s8_field.grid(row=10, column=2, sticky="wens")
        self.s8_button = tk.Button(self.s8_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.s8_button.grid(row=0, column=0, sticky="wens")
        self.s8_field.rowconfigure(0, weight=1)
        self.s8_field.columnconfigure(0, weight=1)

        self.s8_pos = tk.Frame(self, bd=0)
        self.s8_pos.grid(row=11, column=2, sticky="wens")
        self.s8_pos.columnconfigure((0,1,2,3), weight=1)
        self.s8_pos.rowconfigure(0, weight=1)
        self.s8_player_1 = tk.Frame(self.s8_pos, bg=self.back_color)
        self.s8_player_1.grid(row=0, column=0, sticky="wens")
        self.s8_player_2 = tk.Frame(self.s8_pos, bg=self.back_color)
        self.s8_player_2.grid(row=0, column=1, sticky="wens")
        self.s8_player_3 = tk.Frame(self.s8_pos, bg=self.back_color)
        self.s8_player_3.grid(row=0, column=2, sticky="wens")
        self.s8_player_4 = tk.Frame(self.s8_pos, bg=self.back_color)
        self.s8_player_4.grid(row=0, column=3, sticky="wens")


        # west fields

        self.w1_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w1_field.grid(row=9, column=1, sticky="wens")
        self.w1_button = tk.Button(self.w1_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.w1_button.grid(row=0, column=0, sticky="wens")
        self.w1_field.rowconfigure(0, weight=1)
        self.w1_field.columnconfigure(0, weight=1)

        self.w1_pos = tk.Frame(self, bd=0)
        self.w1_pos.grid(row=9, column=0, sticky="wens")
        self.w1_pos.columnconfigure(0, weight=1)
        self.w1_pos.rowconfigure((0,1,2,3), weight=1)
        self.w1_player_1 = tk.Frame(self.w1_pos, bg=self.back_color)
        self.w1_player_1.grid(row=0, column=0, sticky="wens")
        self.w1_player_2 = tk.Frame(self.w1_pos, bg=self.back_color)
        self.w1_player_2.grid(row=1, column=0, sticky="wens")
        self.w1_player_3 = tk.Frame(self.w1_pos, bg=self.back_color)
        self.w1_player_3.grid(row=2, column=0, sticky="wens")
        self.w1_player_4 = tk.Frame(self.w1_pos, bg=self.back_color)
        self.w1_player_4.grid(row=3, column=0, sticky="wens")

        self.w2_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w2_field.grid(row=8, column=1, sticky="wens")
        self.w2_button = tk.Button(self.w2_field, text="", bg=self.electr_color, state=tk.DISABLED)
        self.w2_button.grid(row=0, column=0, sticky="wens")
        self.w2_field.rowconfigure(0, weight=1)
        self.w2_field.columnconfigure(0, weight=1)

        self.w2_pos = tk.Frame(self, bd=0)
        self.w2_pos.grid(row=8, column=0, sticky="wens")
        self.w2_pos.columnconfigure(0, weight=1)
        self.w2_pos.rowconfigure((0,1,2,3), weight=1)
        self.w2_player_1 = tk.Frame(self.w2_pos, bg=self.back_color)
        self.w2_player_1.grid(row=0, column=0, sticky="wens")
        self.w2_player_2 = tk.Frame(self.w2_pos, bg=self.back_color)
        self.w2_player_2.grid(row=1, column=0, sticky="wens")
        self.w2_player_3 = tk.Frame(self.w2_pos, bg=self.back_color)
        self.w2_player_3.grid(row=2, column=0, sticky="wens")
        self.w2_player_4 = tk.Frame(self.w2_pos, bg=self.back_color)
        self.w2_player_4.grid(row=3, column=0, sticky="wens")

        self.w3_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w3_field.grid(row=7, column=1, sticky="wens")
        self.w3_button = tk.Button(self.w3_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.w3_button.grid(row=0, column=0, sticky="wens")
        self.w3_field.rowconfigure(0, weight=1)
        self.w3_field.columnconfigure(0, weight=1)

        self.w3_pos = tk.Frame(self, bd=0)
        self.w3_pos.grid(row=7, column=0, sticky="wens")
        self.w3_pos.columnconfigure(0, weight=1)
        self.w3_pos.rowconfigure((0,1,2,3), weight=1)
        self.w3_player_1 = tk.Frame(self.w3_pos, bg=self.back_color)
        self.w3_player_1.grid(row=0, column=0, sticky="wens")
        self.w3_player_2 = tk.Frame(self.w3_pos, bg=self.back_color)
        self.w3_player_2.grid(row=1, column=0, sticky="wens")
        self.w3_player_3 = tk.Frame(self.w3_pos, bg=self.back_color)
        self.w3_player_3.grid(row=2, column=0, sticky="wens")
        self.w3_player_4 = tk.Frame(self.w3_pos, bg=self.back_color)
        self.w3_player_4.grid(row=3, column=0, sticky="wens")

        self.w4_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w4_field.grid(row=6, column=1, sticky="wens")
        self.w4_button = tk.Button(self.w4_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.w4_button.grid(row=0, column=0, sticky="wens")
        self.w4_field.rowconfigure(0, weight=1)
        self.w4_field.columnconfigure(0, weight=1)

        self.w4_pos = tk.Frame(self, bd=0)
        self.w4_pos.grid(row=6, column=0, sticky="wens")
        self.w4_pos.columnconfigure(0, weight=1)
        self.w4_pos.rowconfigure((0,1,2,3), weight=1)
        self.w4_player_1 = tk.Frame(self.w4_pos, bg=self.back_color)
        self.w4_player_1.grid(row=0, column=0, sticky="wens")
        self.w4_player_2 = tk.Frame(self.w4_pos, bg=self.back_color)
        self.w4_player_2.grid(row=1, column=0, sticky="wens")
        self.w4_player_3 = tk.Frame(self.w4_pos, bg=self.back_color)
        self.w4_player_3.grid(row=2, column=0, sticky="wens")
        self.w4_player_4 = tk.Frame(self.w4_pos, bg=self.back_color)
        self.w4_player_4.grid(row=3, column=0, sticky="wens")

        self.w5_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w5_field.grid(row=5, column=1, sticky="wens")
        self.w5_button = tk.Button(self.w5_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.w5_button.grid(row=0, column=0, sticky="wens")
        self.w5_field.rowconfigure(0, weight=1)
        self.w5_field.columnconfigure(0, weight=1)

        self.w5_pos = tk.Frame(self, bd=0)
        self.w5_pos.grid(row=5, column=0, sticky="wens")
        self.w5_pos.columnconfigure(0, weight=1)
        self.w5_pos.rowconfigure((0,1,2,3), weight=1)
        self.w5_player_1 = tk.Frame(self.w5_pos, bg=self.back_color)
        self.w5_player_1.grid(row=0, column=0, sticky="wens")
        self.w5_player_2 = tk.Frame(self.w5_pos, bg=self.back_color)
        self.w5_player_2.grid(row=1, column=0, sticky="wens")
        self.w5_player_3 = tk.Frame(self.w5_pos, bg=self.back_color)
        self.w5_player_3.grid(row=2, column=0, sticky="wens")
        self.w5_player_4 = tk.Frame(self.w5_pos, bg=self.back_color)
        self.w5_player_4.grid(row=3, column=0, sticky="wens")

        self.w6_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w6_field.grid(row=4, column=1, sticky="wens")
        self.w6_button = tk.Button(self.w6_field, text="", bg=self.food_color, state=tk.DISABLED)
        self.w6_button.grid(row=0, column=0, sticky="wens")
        self.w6_field.rowconfigure(0, weight=1)
        self.w6_field.columnconfigure(0, weight=1)

        self.w6_pos = tk.Frame(self, bd=0)
        self.w6_pos.grid(row=4, column=0, sticky="wens")
        self.w6_pos.columnconfigure(0, weight=1)
        self.w6_pos.rowconfigure((0,1,2,3), weight=1)
        self.w6_player_1 = tk.Frame(self.w6_pos, bg=self.back_color)
        self.w6_player_1.grid(row=0, column=0, sticky="wens")
        self.w6_player_2 = tk.Frame(self.w6_pos, bg=self.back_color)
        self.w6_player_2.grid(row=1, column=0, sticky="wens")
        self.w6_player_3 = tk.Frame(self.w6_pos, bg=self.back_color)
        self.w6_player_3.grid(row=2, column=0, sticky="wens")
        self.w6_player_4 = tk.Frame(self.w6_pos, bg=self.back_color)
        self.w6_player_4.grid(row=3, column=0, sticky="wens")

        self.w7_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w7_field.grid(row=3, column=1, sticky="wens")
        self.w7_button = tk.Button(self.w7_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.w7_button.grid(row=0, column=0, sticky="wens")
        self.w7_field.rowconfigure(0, weight=1)
        self.w7_field.columnconfigure(0, weight=1)

        self.w7_pos = tk.Frame(self, bd=0)
        self.w7_pos.grid(row=3, column=0, sticky="wens")
        self.w7_pos.columnconfigure(0, weight=1)
        self.w7_pos.rowconfigure((0,1,2,3), weight=1)
        self.w7_player_1 = tk.Frame(self.w7_pos, bg=self.back_color)
        self.w7_player_1.grid(row=0, column=0, sticky="wens")
        self.w7_player_2 = tk.Frame(self.w7_pos, bg=self.back_color)
        self.w7_player_2.grid(row=1, column=0, sticky="wens")
        self.w7_player_3 = tk.Frame(self.w7_pos, bg=self.back_color)
        self.w7_player_3.grid(row=2, column=0, sticky="wens")
        self.w7_player_4 = tk.Frame(self.w7_pos, bg=self.back_color)
        self.w7_player_4.grid(row=3, column=0, sticky="wens")

        self.w8_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.w8_field.grid(row=2, column=1, sticky="wens")
        self.w8_button = tk.Button(self.w8_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.w8_button.grid(row=0, column=0, sticky="wens")
        self.w8_field.rowconfigure(0, weight=1)
        self.w8_field.columnconfigure(0, weight=1)

        self.w8_pos = tk.Frame(self, bd=0)
        self.w8_pos.grid(row=2, column=0, sticky="wens")
        self.w8_pos.columnconfigure(0, weight=1)
        self.w8_pos.rowconfigure((0,1,2,3), weight=1)
        self.w8_player_1 = tk.Frame(self.w8_pos, bg=self.back_color)
        self.w8_player_1.grid(row=0, column=0, sticky="wens")
        self.w8_player_2 = tk.Frame(self.w8_pos, bg=self.back_color)
        self.w8_player_2.grid(row=1, column=0, sticky="wens")
        self.w8_player_3 = tk.Frame(self.w8_pos, bg=self.back_color)
        self.w8_player_3.grid(row=2, column=0, sticky="wens")
        self.w8_player_4 = tk.Frame(self.w8_pos, bg=self.back_color)
        self.w8_player_4.grid(row=3, column=0, sticky="wens")


        # east fields

        self.e1_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e1_field.grid(row=2, column=10, sticky="wens")
        self.e1_button = tk.Button(self.e1_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.e1_button.grid(row=0, column=0, sticky="wens")
        self.e1_field.rowconfigure(0, weight=1)
        self.e1_field.columnconfigure(0, weight=1)

        self.e1_pos = tk.Frame(self, bd=0)
        self.e1_pos.grid(row=2, column=11, sticky="wens")
        self.e1_pos.columnconfigure(0, weight=1)
        self.e1_pos.rowconfigure((0,1,2,3), weight=1)
        self.e1_player_1 = tk.Frame(self.e1_pos, bg=self.back_color)
        self.e1_player_1.grid(row=3, column=0, sticky="wens")
        self.e1_player_2 = tk.Frame(self.e1_pos, bg=self.back_color)
        self.e1_player_2.grid(row=2, column=0, sticky="wens")
        self.e1_player_3 = tk.Frame(self.e1_pos, bg=self.back_color)
        self.e1_player_3.grid(row=1, column=0, sticky="wens")
        self.e1_player_4 = tk.Frame(self.e1_pos, bg=self.back_color)
        self.e1_player_4.grid(row=0, column=0, sticky="wens")

        self.e2_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e2_field.grid(row=3, column=10, sticky="wens")
        self.e2_button = tk.Button(self.e2_field, text="", bg=self.electr_color, state=tk.DISABLED)
        self.e2_button.grid(row=0, column=0, sticky="wens")
        self.e2_field.rowconfigure(0, weight=1)
        self.e2_field.columnconfigure(0, weight=1)

        self.e2_pos = tk.Frame(self, bd=0)
        self.e2_pos.grid(row=3, column=11, sticky="wens")
        self.e2_pos.columnconfigure(0, weight=1)
        self.e2_pos.rowconfigure((0,1,2,3), weight=1)
        self.e2_player_1 = tk.Frame(self.e2_pos, bg=self.back_color)
        self.e2_player_1.grid(row=3, column=0, sticky="wens")
        self.e2_player_2 = tk.Frame(self.e2_pos, bg=self.back_color)
        self.e2_player_2.grid(row=2, column=0, sticky="wens")
        self.e2_player_3 = tk.Frame(self.e2_pos, bg=self.back_color)
        self.e2_player_3.grid(row=1, column=0, sticky="wens")
        self.e2_player_4 = tk.Frame(self.e2_pos, bg=self.back_color)
        self.e2_player_4.grid(row=0, column=0, sticky="wens")

        self.e3_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e3_field.grid(row=4, column=10, sticky="wens")
        self.e3_button = tk.Button(self.e3_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.e3_button.grid(row=0, column=0, sticky="wens")
        self.e3_field.rowconfigure(0, weight=1)
        self.e3_field.columnconfigure(0, weight=1)

        self.e3_pos = tk.Frame(self, bd=0)
        self.e3_pos.grid(row=4, column=11, sticky="wens")
        self.e3_pos.columnconfigure(0, weight=1)
        self.e3_pos.rowconfigure((0,1,2,3), weight=1)
        self.e3_player_1 = tk.Frame(self.e3_pos, bg=self.back_color)
        self.e3_player_1.grid(row=3, column=0, sticky="wens")
        self.e3_player_2 = tk.Frame(self.e3_pos, bg=self.back_color)
        self.e3_player_2.grid(row=2, column=0, sticky="wens")
        self.e3_player_3 = tk.Frame(self.e3_pos, bg=self.back_color)
        self.e3_player_3.grid(row=1, column=0, sticky="wens")
        self.e3_player_4 = tk.Frame(self.e3_pos, bg=self.back_color)
        self.e3_player_4.grid(row=0, column=0, sticky="wens")

        self.e4_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e4_field.grid(row=5, column=10, sticky="wens")
        self.e4_button = tk.Button(self.e4_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.e4_button.grid(row=0, column=0, sticky="wens")
        self.e4_field.rowconfigure(0, weight=1)
        self.e4_field.columnconfigure(0, weight=1)

        self.e4_pos = tk.Frame(self, bd=0)
        self.e4_pos.grid(row=5, column=11, sticky="wens")
        self.e4_pos.columnconfigure(0, weight=1)
        self.e4_pos.rowconfigure((0,1,2,3), weight=1)
        self.e4_player_1 = tk.Frame(self.e4_pos, bg=self.back_color)
        self.e4_player_1.grid(row=3, column=0, sticky="wens")
        self.e4_player_2 = tk.Frame(self.e4_pos, bg=self.back_color)
        self.e4_player_2.grid(row=2, column=0, sticky="wens")
        self.e4_player_3 = tk.Frame(self.e4_pos, bg=self.back_color)
        self.e4_player_3.grid(row=1, column=0, sticky="wens")
        self.e4_player_4 = tk.Frame(self.e4_pos, bg=self.back_color)
        self.e4_player_4.grid(row=0, column=0, sticky="wens")

        self.e5_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e5_field.grid(row=6, column=10, sticky="wens")
        self.e5_button = tk.Button(self.e5_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.e5_button.grid(row=0, column=0, sticky="wens")
        self.e5_field.rowconfigure(0, weight=1)
        self.e5_field.columnconfigure(0, weight=1)

        self.e5_pos = tk.Frame(self, bd=0)
        self.e5_pos.grid(row=6, column=11, sticky="wens")
        self.e5_pos.columnconfigure(0, weight=1)
        self.e5_pos.rowconfigure((0,1,2,3), weight=1)
        self.e5_player_1 = tk.Frame(self.e5_pos, bg=self.back_color)
        self.e5_player_1.grid(row=3, column=0, sticky="wens")
        self.e5_player_2 = tk.Frame(self.e5_pos, bg=self.back_color)
        self.e5_player_2.grid(row=2, column=0, sticky="wens")
        self.e5_player_3 = tk.Frame(self.e5_pos, bg=self.back_color)
        self.e5_player_3.grid(row=1, column=0, sticky="wens")
        self.e5_player_4 = tk.Frame(self.e5_pos, bg=self.back_color)
        self.e5_player_4.grid(row=0, column=0, sticky="wens")

        self.e6_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e6_field.grid(row=7, column=10, sticky="wens")
        self.e6_button = tk.Button(self.e6_field, text="", bg=self.food_color, state=tk.DISABLED)
        self.e6_button.grid(row=0, column=0, sticky="wens")
        self.e6_field.rowconfigure(0, weight=1)
        self.e6_field.columnconfigure(0, weight=1)

        self.e6_pos = tk.Frame(self, bd=0)
        self.e6_pos.grid(row=7, column=11, sticky="wens")
        self.e6_pos.columnconfigure(0, weight=1)
        self.e6_pos.rowconfigure((0,1,2,3), weight=1)
        self.e6_player_1 = tk.Frame(self.e6_pos, bg=self.back_color)
        self.e6_player_1.grid(row=3, column=0, sticky="wens")
        self.e6_player_2 = tk.Frame(self.e6_pos, bg=self.back_color)
        self.e6_player_2.grid(row=2, column=0, sticky="wens")
        self.e6_player_3 = tk.Frame(self.e6_pos, bg=self.back_color)
        self.e6_player_3.grid(row=1, column=0, sticky="wens")
        self.e6_player_4 = tk.Frame(self.e6_pos, bg=self.back_color)
        self.e6_player_4.grid(row=0, column=0, sticky="wens")

        self.e7_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e7_field.grid(row=8, column=10, sticky="wens")
        self.e7_button = tk.Button(self.e7_field, text="", bg=self.house_color, state=tk.DISABLED)
        self.e7_button.grid(row=0, column=0, sticky="wens")
        self.e7_field.rowconfigure(0, weight=1)
        self.e7_field.columnconfigure(0, weight=1)

        self.e7_pos = tk.Frame(self, bd=0)
        self.e7_pos.grid(row=8, column=11, sticky="wens")
        self.e7_pos.columnconfigure(0, weight=1)
        self.e7_pos.rowconfigure((0,1,2,3), weight=1)
        self.e7_player_1 = tk.Frame(self.e7_pos, bg=self.back_color)
        self.e7_player_1.grid(row=3, column=0, sticky="wens")
        self.e7_player_2 = tk.Frame(self.e7_pos, bg=self.back_color)
        self.e7_player_2.grid(row=2, column=0, sticky="wens")
        self.e7_player_3 = tk.Frame(self.e7_pos, bg=self.back_color)
        self.e7_player_3.grid(row=1, column=0, sticky="wens")
        self.e7_player_4 = tk.Frame(self.e7_pos, bg=self.back_color)
        self.e7_player_4.grid(row=0, column=0, sticky="wens")

        self.e8_field = tk.Frame(self, highlightbackground=self.player0_color, highlightthickness=7, bd=0)
        self.e8_field.grid(row=9, column=10, sticky="wens")
        self.e8_button = tk.Button(self.e8_field, text="", bg=self.stone_color, state=tk.DISABLED)
        self.e8_button.grid(row=0, column=0, sticky="wens")
        self.e8_field.rowconfigure(0, weight=1)
        self.e8_field.columnconfigure(0, weight=1)

        self.e8_pos = tk.Frame(self, bd=0)
        self.e8_pos.grid(row=9, column=11, sticky="wens")
        self.e8_pos.columnconfigure(0, weight=1)
        self.e8_pos.rowconfigure((0,1,2,3), weight=1)
        self.e8_player_1 = tk.Frame(self.e8_pos, bg=self.back_color)
        self.e8_player_1.grid(row=3, column=0, sticky="wens")
        self.e8_player_2 = tk.Frame(self.e8_pos, bg=self.back_color)
        self.e8_player_2.grid(row=2, column=0, sticky="wens")
        self.e8_player_3 = tk.Frame(self.e8_pos, bg=self.back_color)
        self.e8_player_3.grid(row=1, column=0, sticky="wens")
        self.e8_player_4 = tk.Frame(self.e8_pos, bg=self.back_color)
        self.e8_player_4.grid(row=0, column=0, sticky="wens")


        # some fake buttons to keep the order easier
        self.fake_1 = tk.Button()
        self.fake_2 = tk.Button()
        self.fake_3 = tk.Button()
        self.fake_4 = tk.Button()


        # setting the relative field sizes

        self.rowconfigure((0,11), weight=1)
        self.rowconfigure((1,10), weight=3)
        self.rowconfigure((2,3,4,5,6,7,8,9), weight=2)
        self.columnconfigure((0,11), weight=1)
        self.columnconfigure((1,10), weight=3)
        self.columnconfigure((2,3,4,5,6,7,8,9), weight=2)


        # list all fields
        self.all_positions = [self.se_player_1, self.s1_player_1, self.s2_player_1, self.s3_player_1, self.s4_player_1, self.s5_player_1, self.s6_player_1, self.s7_player_1, self.s8_player_1, \
                              self.sw_player_1, self.w1_player_1, self.w2_player_1, self.w3_player_1, self.w4_player_1, self.w5_player_1, self.w6_player_1, self.w7_player_1, self.w8_player_1, \
                              self.nw_player_1, self.n1_player_1, self.n2_player_1, self.n3_player_1, self.n4_player_1, self.n5_player_1, self.n6_player_1, self.n7_player_1, self.n8_player_1, \
                              self.ne_player_1, self.e1_player_1, self.e2_player_1, self.e3_player_1, self.e4_player_1, self.e5_player_1, self.e6_player_1, self.e7_player_1, self.e8_player_1, \
                              self.se_player_2, self.s1_player_2, self.s2_player_2, self.s3_player_2, self.s4_player_2, self.s5_player_2, self.s6_player_2, self.s7_player_2, self.s8_player_2, \
                              self.sw_player_2, self.w1_player_2, self.w2_player_2, self.w3_player_2, self.w4_player_2, self.w5_player_2, self.w6_player_2, self.w7_player_2, self.w8_player_2, \
                              self.nw_player_2, self.n1_player_2, self.n2_player_2, self.n3_player_2, self.n4_player_2, self.n5_player_2, self.n6_player_2, self.n7_player_2, self.n8_player_2, \
                              self.ne_player_2, self.e1_player_2, self.e2_player_2, self.e3_player_2, self.e4_player_2, self.e5_player_2, self.e6_player_2, self.e7_player_2, self.e8_player_2, \
                              self.se_player_3, self.s1_player_3, self.s2_player_3, self.s3_player_3, self.s4_player_3, self.s5_player_3, self.s6_player_3, self.s7_player_3, self.s8_player_3, \
                              self.sw_player_3, self.w1_player_3, self.w2_player_3, self.w3_player_3, self.w4_player_3, self.w5_player_3, self.w6_player_3, self.w7_player_3, self.w8_player_3, \
                              self.nw_player_3, self.n1_player_3, self.n2_player_3, self.n3_player_3, self.n4_player_3, self.n5_player_3, self.n6_player_3, self.n7_player_3, self.n8_player_3, \
                              self.ne_player_3, self.e1_player_3, self.e2_player_3, self.e3_player_3, self.e4_player_3, self.e5_player_3, self.e6_player_3, self.e7_player_3, self.e8_player_3, \
                              self.se_player_4, self.s1_player_4, self.s2_player_4, self.s3_player_4, self.s4_player_4, self.s5_player_4, self.s6_player_4, self.s7_player_4, self.s8_player_4, \
                              self.sw_player_4, self.w1_player_4, self.w2_player_4, self.w3_player_4, self.w4_player_4, self.w5_player_4, self.w6_player_4, self.w7_player_4, self.w8_player_4, \
                              self.nw_player_4, self.n1_player_4, self.n2_player_4, self.n3_player_4, self.n4_player_4, self.n5_player_4, self.n6_player_4, self.n7_player_4, self.n8_player_4, \
                              self.ne_player_4, self.e1_player_4, self.e2_player_4, self.e3_player_4, self.e4_player_4, self.e5_player_4, self.e6_player_4, self.e7_player_4, self.e8_player_4]

        self.all_fields = [self.se_field, self.s1_field, self.s2_field, self.s3_field, self.s4_field, self.s5_field, self.s6_field, self.s7_field, self.s8_field, \
                           self.sw_field, self.w1_field, self.w2_field, self.w3_field, self.w4_field, self.w5_field, self.w6_field, self.w7_field, self.w8_field, \
                           self.nw_field, self.n1_field, self.n2_field, self.n3_field, self.n4_field, self.n5_field, self.n6_field, self.n7_field, self.n8_field, \
                           self.ne_field, self.e1_field, self.e2_field, self.e3_field, self.e4_field, self.e5_field, self.e6_field, self.e7_field, self.e8_field]

        self.all_buttons = [self.fake_1, self.s1_button, self.s2_button, self.s3_button, self.s4_button, self.s5_button, self.s6_button, self.s7_button, self.s8_button, \
                            self.fake_2, self.w1_button, self.w2_button, self.w3_button, self.w4_button, self.w5_button, self.w6_button, self.w7_button, self.w8_button, \
                            self.fake_3, self.n1_button, self.n2_button, self.n3_button, self.n4_button, self.n5_button, self.n6_button, self.n7_button, self.n8_button, \
                            self.fake_4, self.e1_button, self.e2_button, self.e3_button, self.e4_button, self.e5_button, self.e6_button, self.e7_button, self.e8_button]




